# Joining database tables

In [1]:
from autoencoder.db import get_connection
from autoencoder.db import get_tables
from autoencoder.db import get_columns
from autoencoder.db import query_to_df

## Database schema

In [2]:
conn  = get_connection()
print("Connected to database")

Connected to database

In [3]:
for table in get_tables(conn):
    columns = get_columns(conn, table)
    col_str = ", ".join(f"{name} ({dtype})" for name, dtype in columns)
    print(f"  {table}: {col_str}")

  album_images: album_rowid (INTEGER), width (INTEGER), height (INTEGER), url (TEXT)
  albums: rowid (INTEGER), id (TEXT), fetched_at (INTEGER), name (TEXT), album_type (TEXT), available_markets_rowid (INTEGER), external_id_upc (TEXT), copyright_c (TEXT), copyright_p (TEXT), label (TEXT), popularity (INTEGER), release_date (TEXT), release_date_precision (TEXT), total_tracks (INTEGER), external_id_amgid (TEXT)
  artist_albums: artist_rowid (INTEGER), album_rowid (INTEGER), is_appears_on (INTEGER), is_implicit_appears_on (INTEGER), index_in_album (INTEGER)
  artist_genres: artist_rowid (INTEGER), genre (TEXT)
  artist_images: artist_rowid (INTEGER), width (INTEGER), height (INTEGER), url (TEXT)
  artists: rowid (INTEGER), id (TEXT), fetched_at (INTEGER), name (TEXT), followers_total (INTEGER), popularity (INTEGER)
  audio_features: track_rowid (INT), track_id (TEXT), time_signature (INT), tempo (INT), key (INT), mode (INT), danceability (REAL), energy (REAL), loudness (REAL), speechiness (REAL), acousticness (REAL), instrumentalness (REAL), liveness (REAL), valence (REAL)
  available_markets: rowid (INTEGER), available_markets (TEXT)
  track_artists: track_rowid (INTEGER), artist_rowid (INTEGER)
  tracks: rowid (INTEGER), id (TEXT), fetched_at (INTEGER), name (TEXT), preview_url (TEXT), album_rowid (INTEGER), track_number (INTEGER), external_id_isrc (TEXT), popularity (INTEGER), available_markets_rowid (INTEGER), disc_number (INTEGER), duration_ms (INTEGER), explicit (INTEGER)

In [4]:
tracks = query_to_df(
    conn,
    "SELECT "
    "    t.rowid as track_rowid, "
    "    t.name as track_name, "
    "    t.popularity as track_popularity, "
    "    t.duration_ms, af.time_signature "
    "FROM tracks AS t "
    "INNER JOIN audio_features AS af ON t.rowid = af.rowid "
    "WHERE t.popularity > 95"
)
tracks

,track_rowid,track_name,track_popularity,duration_ms,time_signature
0,290,That’s So True,96,166300,4
1,2779,Not Like Us,96,274192,1
2,2985,BAILE INoLVIDABLE,96,367725,4
3,87640805,Clean Baby Sleep White Noise (Loopable),97,142222,4
4,269,BIRDS OF A FEATHER,98,210373,0
5,2998,DtMF,98,237117,4
6,1178,Die With A Smile,100,251667,4

In [5]:
tracks = query_to_df(
    conn,
    """
    SELECT 
        t.rowid as track_rowid, 
        t.name as track_name, 
        a.name as artist_name 
    FROM tracks AS t 
    INNER JOIN track_artists AS ta ON t.rowid = ta.track_rowid 
    INNER JOIN artists AS a ON ta.artist_rowid = a.rowid 
    WHERE t.popularity > 80
      AND ta.artist_rowid = (
          SELECT artist_rowid
          FROM track_artists 
          WHERE track_rowid = t.rowid
          LIMIT 1 -- for the moment we limit to the track's first artist
      );
    """
)
tracks

      track_rowid                               track_name     artist_name
0              55                                   MUNYUN   Playboi Carti
1              66                                 OPM BABI   Playboi Carti
2             266                                   SKINNY   Billie Eilish
3             585                                Disturbia         Rihanna
4             679                                Von dutch      Charli xcx
...           ...                                      ...             ...
1294         2985                        BAILE INoLVIDABLE       Bad Bunny
1295     87640805  Clean Baby Sleep White Noise (Loopable)  Dream Supplier
1296          269                       BIRDS OF A FEATHER   Billie Eilish
1297         2998                                     DtMF       Bad Bunny
1298         1178                         Die With A Smile       Lady Gaga

[1299 rows x 3 columns]

In [5]:
tracks = query_to_df(
    conn,
    """
    SELECT 
        t.rowid as track_rowid, 
        t.name as track_name, 
        a.name as artist_name, 
        a.rowid as artist_rowid, 
        t.album_rowid, 
        al.name as album_name, 
        al.album_type, 
        al.label, 
        al.release_date, 
        al.release_date_precision, 
        t.external_id_isrc as id_isrc, 
        al.external_id_upc as id_upc, 
        af.time_signature, 
        af.tempo, 
        af.key, 
        af.mode, 
        af.danceability, 
        af.energy, 
        af.loudness, 
        af.speechiness, 
        af.acousticness, 
        af.instrumentalness, 
        af.liveness, 
        af.valence, 
        t.explicit, 
        t.popularity as track_popularity, 
        a.popularity as artist_popularity, 
        a.followers_total as followers, 
        al.popularity as album_popularity, 
        t.duration_ms, 
        t.track_number, 
        t.disc_number, 
        al.total_tracks
    FROM tracks AS t 
    INNER JOIN audio_features AS af ON t.rowid = af.track_rowid
    INNER JOIN albums AS al ON t.album_rowid = al.rowid 
    INNER JOIN track_artists AS ta ON t.rowid = ta.track_rowid -- joint table
    INNER JOIN artists AS a ON ta.artist_rowid = a.rowid 
    WHERE t.popularity > 80
      AND ta.artist_rowid = (
          SELECT artist_rowid
          FROM track_artists 
          WHERE track_rowid = t.rowid
          LIMIT 1 -- for the moment we limit to the track's first artist
      );
    """
)
tracks

,track_rowid,track_name,artist_name,artist_rowid,album_rowid,album_name,album_type,label,release_date,release_date_precision,...,valence,explicit,track_popularity,artist_popularity,followers,album_popularity,duration_ms,track_number,disc_number,total_tracks
0,55,MUNYUN,Playboi Carti,1476081,21,MUSIC,album,AWGE/Interscope Records,2025-03-14,day,...,0.0376,1,81,96,13916270,89,154285,12,1,30
1,66,OPM BABI,Playboi Carti,1476081,21,MUSIC,album,AWGE/Interscope Records,2025-03-14,day,...,0.0405,1,81,96,13916270,89,173076,23,1,30
2,266,SKINNY,Billie Eilish,842869,102,HIT ME HARD AND SOFT,album,Darkroom/Interscope Records,2024-05-17,day,...,0.0395,0,81,95,109602603,94,219733,1,1,10
3,585,Disturbia,Rihanna,1762878,125,Good Girl Gone Bad: Reloaded,album,Def Jam Recordings,2008-06-02,day,...,0.7170,0,81,92,66253125,83,238626,13,1,15
4,679,Von dutch,Charli xcx,5178238,132,BRAT,album,Atlantic Records,2024-06-07,day,...,0.6480,1,81,85,5197966,82,164284,6,1,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1282,2779,Not Like Us,Kendrick Lamar,4765104,358,Not Like Us,single,"Kendrick Lamar, under exclusive license to Int...",2024-05-04,day,...,0.2140,1,96,97,39723389,85,274192,1,1,1
1283,2985,BAILE INoLVIDABLE,Bad Bunny,2713710,373,DeBÍ TiRAR MáS FOToS,album,Rimas Entertainment LLC.,2025-01-05,day,...,0.2190,1,96,100,93195263,100,367725,3,1,17
1284,269,BIRDS OF A FEATHER,Billie Eilish,842869,102,HIT ME HARD AND SOFT,album,Darkroom/Interscope Records,2024-05-17,day,...,0.4380,0,98,95,109602603,94,210373,4,1,10
1285,2998,DtMF,Bad Bunny,2713710,373,DeBÍ TiRAR MáS FOToS,album,Rimas Entertainment LLC.,2025-01-05,day,...,0.0320,1,98,100,93195263,100,237117,16,1,17
1286,1178,Die With A Smile,Lady Gaga,5908777,170,Die With A Smile,single,Interscope,2024-08-16,day,...,0.5350,0,100,94,36284092,89,251667,1,1,1

In [6]:
tracks = query_to_df(
    conn,
    """
    WITH GenreAgg AS (
        SELECT 
            artist_rowid, 
            GROUP_CONCAT(genre, ' | ') AS genre_list
        FROM artist_genres
        GROUP BY artist_rowid
    )
    SELECT 
        t.rowid as track_rowid, 
        t.name as track_name, 
        a.name as artist_name, 
        a.rowid as artist_rowid, 
        t.album_rowid, 
        al.name as album_name, 
        al.album_type, 
        al.label, 
        al.release_date, 
        al.release_date_precision, 
        t.duration_ms, 
        t.track_number, 
        t.disc_number, 
        al.total_tracks, 
        t.external_id_isrc as id_isrc, 
        al.external_id_upc as id_upc, 
        af.time_signature, 
        af.tempo, 
        af.key, 
        af.mode, 
        af.danceability, 
        af.energy, 
        af.loudness, 
        af.speechiness, 
        af.acousticness, 
        af.instrumentalness, 
        af.liveness, 
        af.valence, 
        t.explicit, 
        t.popularity as track_popularity, 
        a.popularity as artist_popularity, 
        a.followers_total as followers, 
        al.popularity as album_popularity, 
        ga.genre_list 
    FROM tracks AS t 
    INNER JOIN audio_features AS af ON t.rowid = af.track_rowid
    INNER JOIN albums AS al ON t.album_rowid = al.rowid 
    INNER JOIN track_artists AS ta ON t.rowid = ta.track_rowid 
    INNER JOIN artists AS a ON ta.artist_rowid = a.rowid 
    LEFT JOIN GenreAgg AS ga ON a.rowid = ga.artist_rowid
    WHERE t.popularity > 80
      AND ta.artist_rowid = (
          SELECT artist_rowid
          FROM track_artists 
          WHERE track_rowid = t.rowid
          LIMIT 1
      );
    """
)
tracks

,track_rowid,track_name,artist_name,artist_rowid,album_rowid,album_name,album_type,label,release_date,release_date_precision,...,acousticness,instrumentalness,liveness,valence,explicit,track_popularity,artist_popularity,followers,album_popularity,genre_list
0,55,MUNYUN,Playboi Carti,1476081,21,MUSIC,album,AWGE/Interscope Records,2025-03-14,day,...,0.000159,0.000035,0.1430,0.0376,1,81,96,13916270,89,rage rap
1,66,OPM BABI,Playboi Carti,1476081,21,MUSIC,album,AWGE/Interscope Records,2025-03-14,day,...,0.000126,0.000004,0.3860,0.0405,1,81,96,13916270,89,rage rap
2,266,SKINNY,Billie Eilish,842869,102,HIT ME HARD AND SOFT,album,Darkroom/Interscope Records,2024-05-17,day,...,0.693000,0.007060,0.0968,0.0395,0,81,95,109602603,94,None
3,585,Disturbia,Rihanna,1762878,125,Good Girl Gone Bad: Reloaded,album,Def Jam Recordings,2008-06-02,day,...,0.086100,0.000000,0.1680,0.7170,0,81,92,66253125,83,None
4,679,Von dutch,Charli xcx,5178238,132,BRAT,album,Atlantic Records,2024-06-07,day,...,0.002980,0.003750,0.1160,0.6480,1,81,85,5197966,82,art pop | hyperpop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1282,2779,Not Like Us,Kendrick Lamar,4765104,358,Not Like Us,single,"Kendrick Lamar, under exclusive license to Int...",2024-05-04,day,...,0.010700,0.000000,0.1410,0.2140,1,96,97,39723389,85,hip hop | west coast hip hop
1283,2985,BAILE INoLVIDABLE,Bad Bunny,2713710,373,DeBÍ TiRAR MáS FOToS,album,Rimas Entertainment LLC.,2025-01-05,day,...,0.192000,0.790000,0.1120,0.2190,1,96,100,93195263,100,latin | reggaeton | trap latino | urbano latino
1284,269,BIRDS OF A FEATHER,Billie Eilish,842869,102,HIT ME HARD AND SOFT,album,Darkroom/Interscope Records,2024-05-17,day,...,0.200000,0.060800,0.1170,0.4380,0,98,95,109602603,94,None
1285,2998,DtMF,Bad Bunny,2713710,373,DeBÍ TiRAR MáS FOToS,album,Rimas Entertainment LLC.,2025-01-05,day,...,0.177000,0.218000,0.0807,0.0320,1,98,100,93195263,100,latin | reggaeton | trap latino | urbano latino
1286,1178,Die With A Smile,Lady Gaga,5908777,170,Die With A Smile,single,Interscope,2024-08-16,day,...,0.308000,0.000000,0.1220,0.5350,0,100,94,36284092,89,art pop | pop